---
- hosts: localhost
  become: true
  tasks:
  
  - name: Set device role from hostname
    set_fact:
      device_role: >-
        {{ 'workstation' if 'wks' in ansible_hostname
          else 'servers' if 'srv' in ansible_hostname
          else 'undefined' }}

  roles:
  - workstations
  - servers
