---
config_repo_url: https://github.com/h1dden30/ansible.git 

netbox_docker_repo: https://github.com/netbox-community/netbox-docker.git
netbox_install_dir: /opt/netbox-docker
netbox_superuser_name: admin
netbox_superuser_email: admin@ebadkhan.dev

