#!/bin/bash
cat /etc/motd-art.txt
echo ""
echo "  Host:     $(hostname)"
echo "  OS:       $(lsb_release -ds)"
echo "  Kernel:   $(uname -r)"
echo "  Uptime:   $(uptime -p)"
echo "  Disk:     $(df -h / | awk 'NR==2 {print $3"/"$2" ("$5" used)"}')"
echo "  Memory:   $(free -h | awk '/^Mem:/ {print $3"/"$2}')"
echo ""