---

  - name: Install packages
    ansible.builtin.apt:
      name:
      - btop
      - tmux
      state: present

  - name: Deploy ansible-pull service unit
    ansible.builtin.copy:
     src: ansible-server-update.service
     dest: /etc/systemd/system/ansible-server-update.service
     owner: root
     group: root
     mode: '0644'
    notify: reload systemd


  - name: Deploy ansible-pull timer unit
    ansible.builtin.copy:
     src: ansible-server-update.timer
     dest: /etc/systemd/system/ansible-server-update.timer
     owner: root
     group: root
     mode: '0644'
    notify: reload systemd

  - name: Enable and start the timer
    ansible.builtin.systemd:
      name: ansible-server-update.timer
      enabled: true
      state: started
      daemon_reload: true