---

  - name: Update all packages
    apt:
      update_cache: yes
      upgrade: safe

  - name: Install packages
    apt:
      name:
      - btop
      - tmux
      state: present

  - name: Disable root account
    user: 
      name: root
      password_lock: true
