---

  - name: Install packages
    apt:
      name:
      - btop
      - tmux
      state: present

  - name: Disable root account
    user: 
      name: root
      password_lock: true
  
  - name: Deploy MOTD ASCII art
    ansible.builtin.copy:
     src: motd-art.txt
     dest: /etc/motd-art.txt
     owner: root
     group: root
     mode: '0644'

  - name: Deploy dynamic MOTD script
    ansible.builtin.template:
     src: 99-custom-motd.j2
     dest: /etc/update-motd.d/99-custom-motd
     owner: root
     group: root
     mode: '0755'

  - name: Disable default Ubuntu MOTD noise
    ansible.builtin.file:
     path: "/etc/update-motd.d/{{ item }}"
     mode: '0644'
    loop:
     - 00-header
     - 10-help-text
     - 50-motd-news
     - 91-release-upgrade
     - 60-unminimize
    ignore_errors: true 