---

  - name: Update all packages
    community.general.pacman:
      update_cache: true
      upgrade: true

  - name: Install KDE and other packages
    community.general.pacman:
      name:
        - plasma
        - sdmm
        - konsole
        - code
        - dolphin 
      state: present

  - name: Install prereqs
    community.general.pacman:
      name: 
       - base-devel
       - git
       - sudo
      state: present
  
  - name: Create AUR builder user
    ansible.builtin.user:
      name: aurbuilder
      groups: wheel
      create_home: true

  - name: Allow aurbuilder to use pacman without password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/aurbuilder
      line: "aurbuilder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
      create: true
      mode: '0440'

  - name: Check if yay is installed
    ansible.builtin.command: which yay
    register: yay_check
    changed_when: false
    failed_when: false

  - name: Install yay AUR helper
    when: yay_check.rc != 0
    become_user: aurbuilder
    block:

        - name: Clone yay repository
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay-bin.git
            dest: /tmp/yay-bin

        - name: Build and install yay
          ansible.builtin.command: makepkg -si --noconfirm
          args:
            chdir: /tmp/yay-bin
          changed_when: true

  - name: Install Zen Browser
    become: false
    become_user: aurbuilder
    kewlfft.aur.aur:
      name: zen-browser-bin
      use: yay
      state: present


 # - name: Add shortcut for screenshot -> winkey + shift + 4 screenshot application? or is that included in kde
